apiVersion: v1
kind: PersistentVolume
metadata:
  name: shiori-pv
  namespace: shiori
spec:
  storageClassName: ""
  claimRef:
    name: shiori-pvc
    namespace: shiori
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker
